## Load Datasets

In [1]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

### Parcel Data

In [3]:
# every parcel in King County, around 628k rows:
# Lot size, zoning, view ratings, district name. We can filter to Seattle.
parcels = pd.read_csv('C:/Users/jacob/Downloads/Parcel/EXTR_Parcel.csv', encoding='latin1', low_memory=False)

In [6]:
parcels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 628042 entries, 0 to 628041
Data columns (total 81 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Major                   628042 non-null  int64
 1   Minor                   628042 non-null  int64
 2   PropName                606748 non-null  object
 3   PlatName                533743 non-null  object
 4   PlatLot                 628042 non-null  object
 5   PlatBlock               628042 non-null  object
 6   Range                   628042 non-null  int64
 7   Township                628042 non-null  int64
 8   Section                 628042 non-null  int64
 9   QuarterSection          628042 non-null  object
 10  PropType                628042 non-null  object
 11  Area                    627995 non-null  float64
 12  SubArea                 627995 non-null  float64
 13  SpecArea                19090 non-null   float64
 14  SpecSubArea             19090 non-null   float64
 15  DistrictName            628042 non-null  object
 16  LevyCode                628042 non-null  int64
 17  CurrentZoning           628041 non-null  object
 18  HBUAsIfVacant           628042 non-null  int64
 19  HBUAsImproved           628042 non-null  int64
 20  PresentUse              628042 non-null  int64
 21  SqFtLot                 628042 non-null  int64
 22  WaterSystem             628042 non-null  int64
 23  SewerSystem             628042 non-null  int64
 24  Access                  628042 non-null  int64
 25  Topography              628042 non-null  int64
 26  StreetSurface           628042 non-null  int64
 27  RestrictiveSzShape      628042 non-null  int64
 28  InadequateParking       628042 non-null  int64
 29  PcntUnusable            628042 non-null  int64
 30  Unbuildable             628042 non-null  bool
 31  MtRainier               628042 non-null  int64
 32  Olympics                628042 non-null  int64
 33  Cascades                628042 non-null  int64
 34  Territorial             628042 non-null  int64
 35  SeattleSkyline          628042 non-null  int64
 36  PugetSound              628042 non-null  int64
 37  LakeWashington          628042 non-null  int64
 38  LakeSammamish           628042 non-null  int64
 39  SmallLakeRiverCreek     628042 non-null  int64
 40  OtherView               628042 non-null  int64
 41  WfntLocation            628042 non-null  int64
 42  WfntFootage             628042 non-null  int64
 43  WfntBank                628042 non-null  int64
 44  WfntPoorQuality         628042 non-null  int64
 45  WfntRestrictedAccess    628042 non-null  int64
 46  WfntAccessRights        628042 non-null  object
 47  WfntProximityInfluence  628042 non-null  object
 48  TidelandShoreland       628042 non-null  int64
 49  LotDepthFactor          628042 non-null  int64
 50  TrafficNoise            628042 non-null  int64
 51  AirportNoise            628042 non-null  int64
 52  PowerLines              628042 non-null  object
 53  OtherNuisances          628042 non-null  object
 54  NbrBldgSites            628042 non-null  int64
 55  Contamination           628042 non-null  int64
 56  DNRLease                628042 non-null  object
 57  AdjacentGolfFairway     628042 non-null  object
 58  AdjacentGreenbelt       628042 non-null  object
 59  HistoricSite            628042 non-null  int64
 60  CurrentUseDesignation   628042 non-null  int64
 61  NativeGrowthProtEsmt    628042 non-null  object
 62  Easements               628042 non-null  object
 63  OtherDesignation        628042 non-null  object
 64  DeedRestrictions        628042 non-null  object
 65  DevelopmentRightsPurch  628042 non-null  object
 66  CoalMineHazard          628042 non-null  object
 67  CriticalDrainage        628042 non-null  object
 68  ErosionHazard           628042 non-null  object
 69  LandfillBuffer          628042 non-null  object
 70  HundredYrFloodPlain     628042 non-null  object
 71  SeismicHazard           628042 non-null  object
 72  LandslideHazard         628042 non-null  object
 73  SteepSlopeHazard        628042 non-null  object
 74  Stream                  628042 non-null  object
 75  Wetland                 628042 non-null  object
 76  SpeciesOfConcern        628042 non-null  object
 77  SensitiveAreaTract      628042 non-null  object
 78  WaterProblems           628042 non-null  object
 79  TranspConcurrency       628042 non-null  object
 80  OtherProblems           628042 non-null  object
dtypes: bool(1), float64(4), int64(41), object(35)
memory usage: 383.9+ MB

In [7]:
parcels['DistrictName'].unique()

array(['AUBURN', 'FEDERAL WAY', 'KENT', 'MERCER ISLAND', 'SEATTLE',
       'KENMORE', 'KING COUNTY', 'BELLEVUE', 'RENTON', 'BLACK DIAMOND',
       'BOTHELL', 'BURIEN', 'WOODINVILLE', 'SHORELINE', 'SAMMAMISH',
       'ISSAQUAH', 'NORMANDY PARK', 'TUKWILA', 'NEWCASTLE', 'DES MOINES',
       'KIRKLAND', 'DUVALL', 'SNOQUALMIE', 'REDMOND', 'COVINGTON',
       'PACIFIC', 'SeaTac', 'MAPLE VALLEY', 'LAKE FOREST PARK',
       'CLYDE HILL', 'ENUMCLAW', 'CARNATION', 'BEAUX ARTS', 'NORTH BEND',
       'MEDINA', 'YARROW POINT', 'ALGONA', 'SKYKOMISH', 'MILTON',
       'HUNTS POINT'], dtype=object)

In [8]:
parcels = parcels[parcels['DistrictName'] == 'SEATTLE']

In [9]:
parcels.shape

(189148, 81)

In [10]:
parcels.columns

Index(['Major', 'Minor', 'PropName', 'PlatName', 'PlatLot', 'PlatBlock',
       'Range', 'Township', 'Section', 'QuarterSection', 'PropType', 'Area',
       'SubArea', 'SpecArea', 'SpecSubArea', 'DistrictName', 'LevyCode',
       'CurrentZoning', 'HBUAsIfVacant', 'HBUAsImproved', 'PresentUse',
       'SqFtLot', 'WaterSystem', 'SewerSystem', 'Access', 'Topography',
       'StreetSurface', 'RestrictiveSzShape', 'InadequateParking',
       'PcntUnusable', 'Unbuildable', 'MtRainier', 'Olympics', 'Cascades',
       'Territorial', 'SeattleSkyline', 'PugetSound', 'LakeWashington',
       'LakeSammamish', 'SmallLakeRiverCreek', 'OtherView', 'WfntLocation',
       'WfntFootage', 'WfntBank', 'WfntPoorQuality', 'WfntRestrictedAccess',
       'WfntAccessRights', 'WfntProximityInfluence', 'TidelandShoreland',
       'LotDepthFactor', 'TrafficNoise', 'AirportNoise', 'PowerLines',
       'OtherNuisances', 'NbrBldgSites', 'Contamination', 'DNRLease',
       'AdjacentGolfFairway', 'AdjacentGreenbelt', 'HistoricSite',
       'CurrentUseDesignation', 'NativeGrowthProtEsmt', 'Easements',
       'OtherDesignation', 'DeedRestrictions', 'DevelopmentRightsPurch',
       'CoalMineHazard', 'CriticalDrainage', 'ErosionHazard', 'LandfillBuffer',
       'HundredYrFloodPlain', 'SeismicHazard', 'LandslideHazard',
       'SteepSlopeHazard', 'Stream', 'Wetland', 'SpeciesOfConcern',
       'SensitiveAreaTract', 'WaterProblems', 'TranspConcurrency',
       'OtherProblems'],
      dtype='object')

In [11]:
parcels['DistrictName'].unique()

array(['SEATTLE'], dtype=object)

In [12]:
cols_parcels = ['Major', 'Minor', 'CurrentZoning', 'SqFtLot']
parcels = parcels[cols_parcels]

In [13]:
parcels.shape

(189148, 4)

### Residential Building Data

In [15]:
# every residential building, around 532k rows. Square footage, year built, building grade, bedrooms, 
# bathrooms, condition; it also carries the property address and ZIP code
resbldg = pd.read_csv('C:/Users/jacob/Downloads/Residential Building/EXTR_ResBldg.csv', low_memory=False)

In [16]:
resbldg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 532028 entries, 0 to 532027
Data columns (total 50 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Major               532028 non-null  int64
 1   Minor               532028 non-null  int64
 2   BldgNbr             532028 non-null  int64
 3   NbrLivingUnits      532028 non-null  int64
 4   Address             532028 non-null  object
 5   BuildingNumber      532028 non-null  object
 6   Fraction            532028 non-null  object
 7   DirectionPrefix     531841 non-null  object
 8   StreetName          532028 non-null  object
 9   StreetType          532028 non-null  object
 10  DirectionSuffix     531841 non-null  object
 11  ZipCode             476557 non-null  object
 12  Stories             532028 non-null  float64
 13  BldgGrade           532028 non-null  int64
 14  BldgGradeVar        532028 non-null  int64
 15  SqFt1stFloor        532028 non-null  int64
 16  SqFtHalfFloor       532028 non-null  int64
 17  SqFt2ndFloor        532028 non-null  int64
 18  SqFtUpperFloor      532028 non-null  int64
 19  SqFtUnfinFull       532028 non-null  int64
 20  SqFtUnfinHalf       532028 non-null  int64
 21  SqFtTotLiving       532028 non-null  int64
 22  SqFtTotBasement     532028 non-null  int64
 23  SqFtFinBasement     532028 non-null  int64
 24  FinBasementGrade    532028 non-null  int64
 25  SqFtGarageBasement  532028 non-null  int64
 26  SqFtGarageAttached  532028 non-null  int64
 27  DaylightBasement    532028 non-null  object
 28  SqFtOpenPorch       532028 non-null  int64
 29  SqFtEnclosedPorch   532028 non-null  int64
 30  SqFtDeck            532028 non-null  int64
 31  HeatSystem          532028 non-null  int64
 32  HeatSource          532028 non-null  int64
 33  BrickStone          532028 non-null  int64
 34  ViewUtilization     532028 non-null  object
 35  Bedrooms            532028 non-null  int64
 36  BathHalfCount       532028 non-null  int64
 37  Bath3qtrCount       532028 non-null  int64
 38  BathFullCount       532028 non-null  int64
 39  FpSingleStory       532028 non-null  int64
 40  FpMultiStory        532028 non-null  int64
 41  FpFreestanding      532028 non-null  int64
 42  FpAdditional        532028 non-null  int64
 43  YrBuilt             532028 non-null  int64
 44  YrRenovated         532028 non-null  int64
 45  PcntComplete        532028 non-null  int64
 46  Obsolescence        532028 non-null  int64
 47  PcntNetCondition    532028 non-null  int64
 48  Condition           532028 non-null  int64
 49  AddnlCost           532028 non-null  int64
dtypes: float64(1), int64(39), object(10)
memory usage: 203.0+ MB

In [17]:
resbldg.columns

Index(['Major', 'Minor', 'BldgNbr', 'NbrLivingUnits', 'Address',
       'BuildingNumber', 'Fraction', 'DirectionPrefix', 'StreetName',
       'StreetType', 'DirectionSuffix', 'ZipCode', 'Stories', 'BldgGrade',
       'BldgGradeVar', 'SqFt1stFloor', 'SqFtHalfFloor', 'SqFt2ndFloor',
       'SqFtUpperFloor', 'SqFtUnfinFull', 'SqFtUnfinHalf', 'SqFtTotLiving',
       'SqFtTotBasement', 'SqFtFinBasement', 'FinBasementGrade',
       'SqFtGarageBasement', 'SqFtGarageAttached', 'DaylightBasement',
       'SqFtOpenPorch', 'SqFtEnclosedPorch', 'SqFtDeck', 'HeatSystem',
       'HeatSource', 'BrickStone', 'ViewUtilization', 'Bedrooms',
       'BathHalfCount', 'Bath3qtrCount', 'BathFullCount', 'FpSingleStory',
       'FpMultiStory', 'FpFreestanding', 'FpAdditional', 'YrBuilt',
       'YrRenovated', 'PcntComplete', 'Obsolescence', 'PcntNetCondition',
       'Condition', 'AddnlCost'],
      dtype='object')

In [19]:
cols_resbldg = ['Major', 'Minor', 'NbrLivingUnits', 'ZipCode', 'Stories', 'BldgGrade', 'SqFtTotLiving',
                'SqFtGarageAttached', 'Bedrooms', 'BathFullCount', 'YrBuilt', 'YrRenovated', 'Condition']
resbldg = resbldg[cols_resbldg]

### Real Property Account Data

In [22]:
# tax accounts, around 739k rows; appraised land value, improvement value, taxable values
rpacct = pd.read_csv('C:/Users/jacob/Downloads/Real Property Account/EXTR_RPAcct_NoName.csv', encoding='latin1', 
                     low_memory=False)

In [23]:
rpacct.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 739488 entries, 0 to 739487
Data columns (total 16 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   AcctNbr              739488 non-null  int64
 1   Major                739488 non-null  int64
 2   Minor                739488 non-null  int64
 3   AttnLine             617078 non-null  object
 4   AddrLine             738852 non-null  object
 5   CityState            739488 non-null  object
 6   ZipCode              739488 non-null  int64
 7   LevyCode             739488 non-null  int64
 8   TaxStat              739488 non-null  object
 9   BillYr               739488 non-null  int64
 10  NewConstructionFlag  717745 non-null  object
 11  TaxValReason         739488 non-null  object
 12  ApprLandVal          739488 non-null  int64
 13  ApprImpsVal          739488 non-null  int64
 14  TaxableLandVal       739488 non-null  int64
 15  TaxableImpsVal       739488 non-null  int64
dtypes: int64(10), object(6)
memory usage: 90.3+ MB

In [24]:
rpacct.columns

Index(['AcctNbr', 'Major', 'Minor', 'AttnLine', 'AddrLine', 'CityState',
       'ZipCode', 'LevyCode', 'TaxStat', 'BillYr', 'NewConstructionFlag',
       'TaxValReason', 'ApprLandVal', 'ApprImpsVal', 'TaxableLandVal',
       'TaxableImpsVal'],
      dtype='object')

In [25]:
cols_rpacct = ['Major', 'Minor', 'ApprLandVal', 'ApprImpsVal', 'TaxableLandVal', 'TaxableImpsVal']
rpacct = rpacct[cols_rpacct]

In [26]:
rpacct.shape

(739488, 6)

### Join Datasets

In [27]:
df = parcels.copy()

In [28]:
df = df.merge(resbldg, on=['Major', 'Minor'], how='left')

In [29]:
df = df.merge(rpacct, on=['Major', 'Minor'], how='left')

In [32]:
df.shape

(193279, 19)

In [31]:
df.columns

Index(['Major', 'Minor', 'CurrentZoning', 'SqFtLot', 'NbrLivingUnits',
       'ZipCode', 'Stories', 'BldgGrade', 'SqFtTotLiving',
       'SqFtGarageAttached', 'Bedrooms', 'BathFullCount', 'YrBuilt',
       'YrRenovated', 'Condition', 'ApprLandVal', 'ApprImpsVal',
       'TaxableLandVal', 'TaxableImpsVal'],
      dtype='object')

In [33]:
df.head()

,Major,Minor,CurrentZoning,SqFtLot,NbrLivingUnits,ZipCode,Stories,BldgGrade,SqFtTotLiving,SqFtGarageAttached,Bedrooms,BathFullCount,YrBuilt,YrRenovated,Condition,ApprLandVal,ApprImpsVal,TaxableLandVal,TaxableImpsVal
0,982870,2753,LR3 (M1),500,1.0,98122,3.0,8.0,1080.0,0.0,2.0,2.0,2021.0,0.0,3.0,340000.0,280000.0,340000.0,280000.0
1,57900,1110,NR3,6322,1.0,98117,1.0,8.0,2320.0,230.0,3.0,1.0,1954.0,0.0,3.0,615000.0,390000.0,615000.0,390000.0
2,287710,4110,NC2-55 (M),3960,1.0,98103,1.5,7.0,1780.0,0.0,4.0,1.0,1925.0,0.0,3.0,0.0,300.0,0.0,0.0
3,287710,4110,NC2-55 (M),3960,1.0,98103,1.5,7.0,1780.0,0.0,4.0,1.0,1925.0,0.0,3.0,1279000.0,700.0,376000.0,128900.0
4,390410,230,NR3,6750,1.0,98118,1.0,6.0,660.0,0.0,2.0,1.0,1918.0,0.0,3.0,308000.0,150000.0,308000.0,150000.0

The data on housing is now fully combined into a single dataset.

### ACS Data

Below, we import five different ACS datasets of demographic data for King County census tracts. These datasets are then adjusted to ensure each row represents a given census tract. They are then all merged together into a single DataFrame ``acs``.

In [36]:
income = pd.read_csv('C:/Users/jacob/Downloads/B19013.csv')
tenure = pd.read_csv('C:/Users/jacob/Downloads/B25003.csv')
race = pd.read_csv('C:/Users/jacob/Downloads/B02001.csv')
home_value = pd.read_csv('C:/Users/jacob/Downloads/B25077.csv')
rent_burden = pd.read_csv('C:/Users/jacob/Downloads/B25070.csv')

In [40]:
tenure.head()

,Label (Grouping),Census Tract 1.01; King County; Washington!!Estimate,Census Tract 1.01; King County; Washington!!Margin of Error,Census Tract 1.02; King County; Washington!!Estimate,Census Tract 1.02; King County; Washington!!Margin of Error,Census Tract 2.01; King County; Washington!!Estimate,Census Tract 2.01; King County; Washington!!Margin of Error,Census Tract 2.02; King County; Washington!!Estimate,Census Tract 2.02; King County; Washington!!Margin of Error,Census Tract 3; King County; Washington!!Estimate,...,Census Tract 327.04; King County; Washington!!Estimate,Census Tract 327.04; King County; Washington!!Margin of Error,Census Tract 327.05; King County; Washington!!Estimate,Census Tract 327.05; King County; Washington!!Margin of Error,Census Tract 327.06; King County; Washington!!Estimate,Census Tract 327.06; King County; Washington!!Margin of Error,Census Tract 328; King County; Washington!!Estimate,Census Tract 328; King County; Washington!!Margin of Error,Census Tract 9901; King County; Washington!!Estimate,Census Tract 9901; King County; Washington!!Margin of Error
0,Total:,"1,746",±283,"2,358",±294,"2,486",±387,"1,549",±136,"1,201",...,"2,937",±269,"1,281",±164,874,±100,994,±217,0,±13
1,Owner occupied,141,±68,840,±237,"1,269",±358,"1,131",±111,865,...,"2,347",±247,"1,051",±159,809,±104,887,±211,0,±13
2,Renter occupied,"1,605",±286,"1,518",±263,"1,217",±266,418,±148,336,...,590,±165,230,±115,65,±54,107,±47,0,±13

In [41]:
tenure = tenure.loc[:, ~tenure.columns.str.contains('Margin')]

In [42]:
tenure = tenure.set_index("Label (Grouping)")

In [44]:
tenure = tenure.T

In [45]:
tenure.head()

Label (Grouping),Total:,Owner occupied,Renter occupied
Census Tract 1.01; King County; Washington!!Estimate,"1,746",141,"1,605"
Census Tract 1.02; King County; Washington!!Estimate,"2,358",840,"1,518"
Census Tract 2.01; King County; Washington!!Estimate,"2,486","1,269","1,217"
Census Tract 2.02; King County; Washington!!Estimate,"1,549","1,131",418
Census Tract 3; King County; Washington!!Estimate,"1,201",865,336

In [47]:
income = income.loc[:, ~income.columns.str.contains('Margin')]

In [48]:
income = income.set_index('Label (Grouping)')
income = income.T

In [49]:
income.head()

Label (Grouping)                                   Median household income in the past 12 months (in 2024 inflation-adjusted dollars)
Census Tract 1.01; King County; Washington!!Est...                                             69,577
Census Tract 1.02; King County; Washington!!Est...                                             89,840
Census Tract 2.01; King County; Washington!!Est...                                             88,833
Census Tract 2.02; King County; Washington!!Est...                                            138,472
Census Tract 3; King County; Washington!!Estimate                                             135,536

In [51]:
race = race.loc[:, ~race.columns.str.contains('Margin')]

In [52]:
race = race.set_index('Label (Grouping)')
race = race.T

In [53]:
race.head()

Label (Grouping),Total:,White alone,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some Other Race alone,Two or More Races:,Two races including Some Other Race,"Two races excluding Some Other Race, and three or more races"
Census Tract 1.01; King County; Washington!!Estimate,"3,417","1,693",652,0,422,0,131,519,199,320
Census Tract 1.02; King County; Washington!!Estimate,"4,321","3,121",362,0,431,0,226,181,49,132
Census Tract 2.01; King County; Washington!!Estimate,"4,953","2,594",356,41,980,0,611,371,253,118
Census Tract 2.02; King County; Washington!!Estimate,"4,404","2,165",374,6,708,0,340,811,520,291
Census Tract 3; King County; Washington!!Estimate,"2,926","1,797",179,11,612,1,23,303,97,206

In [55]:
home_value = home_value.loc[:, ~home_value.columns.str.contains('Margin')]

In [56]:
home_value = home_value.set_index('Label (Grouping)')
home_value = home_value.T

In [57]:
home_value.head()

Label (Grouping)                                   Median value (dollars)
Census Tract 1.01; King County; Washington!!Est...                791,700
Census Tract 1.02; King County; Washington!!Est...                985,800
Census Tract 2.01; King County; Washington!!Est...                738,600
Census Tract 2.02; King County; Washington!!Est...                792,500
Census Tract 3; King County; Washington!!Estimate                 678,600

In [58]:
rent_burden = rent_burden.loc[:, ~rent_burden.columns.str.contains('Margin')]

In [59]:
rent_burden = rent_burden.set_index('Label (Grouping)')
rent_burden = rent_burden.T

In [60]:
rent_burden.head()

Label (Grouping),Total:,Less than 10.0 percent,10.0 to 14.9 percent,15.0 to 19.9 percent,20.0 to 24.9 percent,25.0 to 29.9 percent,30.0 to 34.9 percent,35.0 to 39.9 percent,40.0 to 49.9 percent,50.0 percent or more,Not computed
Census Tract 1.01; King County; Washington!!Estimate,"1,605",24,93,210,328,188,80,198,140,294,50
Census Tract 1.02; King County; Washington!!Estimate,"1,518",30,35,106,226,166,156,67,313,320,99
Census Tract 2.01; King County; Washington!!Estimate,"1,217",24,43,168,52,136,111,151,246,209,77
Census Tract 2.02; King County; Washington!!Estimate,418,46,0,68,9,44,7,7,27,150,60
Census Tract 3; King County; Washington!!Estimate,336,11,23,105,27,54,20,0,48,41,7

In [61]:
# set each index as new column
income = income.reset_index()
tenure = tenure.reset_index()
race = race.reset_index()
home_value = home_value.reset_index()
rent_burden = rent_burden.reset_index()

In [62]:
income = income.rename(columns={income.columns[0]: 'tractID'})
tenure = tenure.rename(columns={tenure.columns[0]: 'tractID'})
race = race.rename(columns={race.columns[0]: 'tractID'})
home_value = home_value.rename(columns={home_value.columns[0]: 'tractID'})
rent_burden = rent_burden.rename(columns={rent_burden.columns[0]: 'tractID'})

In [65]:
tenure.head()

Label (Grouping),tractID,Total:,Owner occupied,Renter occupied
0,Census Tract 1.01; King County; Washington!!Es...,"1,746",141,"1,605"
1,Census Tract 1.02; King County; Washington!!Es...,"2,358",840,"1,518"
2,Census Tract 2.01; King County; Washington!!Es...,"2,486","1,269","1,217"
3,Census Tract 2.02; King County; Washington!!Es...,"1,549","1,131",418
4,Census Tract 3; King County; Washington!!Estimate,"1,201",865,336

Clean up tract ID

In [67]:
income['tractID'] = income['tractID'].str.extract(r'Census Tract ([0-9.]+)')

In [68]:
income.head()

Label (Grouping),tractID,Median household income in the past 12 months (in 2024 inflation-adjusted dollars)
0,1.01,"69,577"
1,1.02,"89,840"
2,2.01,"88,833"
3,2.02,"138,472"
4,3,"135,536"

In [69]:
tenure['tractID'] = tenure['tractID'].str.extract(r'Census Tract ([0-9.]+)')
race['tractID'] = race['tractID'].str.extract(r'Census Tract ([0-9.]+)')
home_value['tractID'] = home_value['tractID'].str.extract(r'Census Tract ([0-9.]+)')
rent_burden['tractID'] = rent_burden['tractID'].str.extract(r'Census Tract ([0-9.]+)')

In [70]:
acs = income.copy()

In [71]:
acs = acs.merge(tenure, on=['tractID'], how='inner')
acs = acs.merge(race, on=['tractID'], how='inner')
acs = acs.merge(home_value, on=['tractID'], how='inner')
acs = acs.merge(rent_burden, on=['tractID'], how='inner')

In [72]:
acs.shape

(495, 27)

In [85]:
acs['tractID'].nunique()

495

### Shapefiles of Parcel and Tract Data

In [99]:
import geopandas as gpd

# parcel shape file from https://gis-kingcounty.opendata.arcgis.com/datasets/b86f43b50cb141529113eb5173464e89_0/explore?location=47.613857%2C-122.312690%2C13
parcel_shape = gpd.read_file('C:/Users/jacob/Downloads/parcel_shape/King_County_Parcels.shp')

C:\Users\jacob\anaconda3\Lib\site-packages\pyogrio\raw.py:200: RuntimeWarning: C:/Users/jacob/Downloads/parcel_shape/King_County_Parcels.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

In [100]:
# census tract shape file from https://www.census.gov/cgi-bin/geo/shapefiles/index.php
tract_shape = gpd.read_file('C:/Users/jacob/Downloads/wa_census_tract_shape/tl_2024_53_tract.shp')

In [101]:
tract_shape.columns

Index(['STATEFP', 'COUNTYFP', 'TRACTCE', 'GEOID', 'GEOIDFQ', 'NAME',
       'NAMELSAD', 'MTFCC', 'FUNCSTAT', 'ALAND', 'AWATER', 'INTPTLAT',
       'INTPTLON', 'geometry'],
      dtype='object')

In [102]:
tract_shape = tract_shape[tract_shape['COUNTYFP'] == '033'] # just King County